apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-video-service-config
data:
  DB_HOST: "{{ .Values.db.host }}"
  DB_PORT: "{{ .Values.db.port }}"
  DB_NAME: "{{ .Values.db.name }}"
  RABBITMQ_QUEUE: "{{ .Values.rabbitmq.queueName }}"
  RABBITMQ_HOST: "{{ .Values.rabbitmq.host }}"
  RABBITMQ_PORT: "{{ .Values.rabbitmq.port }}"