apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name}}-video-service-secret
type: Opaque  # Тип для произвольных данных
stringData: 
  DB_USER: "{{ .Values.db.user }}"
  DB_PASS: "{{ .Values.db.pass }}"
  RABBITMQ_USER: "{{ .Values.rabbitmq.user }}"
  RABBITMQ_PASSWORD: "{{ .Values.rabbitmq.password }}"
