apiVersion: apps/v1         # Версия API для Deployment
kind: Deployment            # Тип ресурса — Deployment
metadata:
  name: {{ .Release.Name}}-video-service  # Имя деплоймента
  labels:
    app: video-service            # Лейбл для связи с Service
spec:
  replicas: {{ .Values.replicaCount }}              # Количество копий Pod'ов
  selector:
    matchLabels:
      app: {{ .Release.Name}}-video-service         # Выбор Pod'ов по лейблу
  template:                # Шаблон Pod'а
    metadata:
      labels:
        app: {{ .Release.Name}}-video-service     # Лейбл Pod'а (должен совпадать с selector.matchLabels)
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:13-alpine
        command: ['sh', '-c', 'until pg_isready -h $DB_HOST -p $DB_PORT; do echo "Waiting for DB..."; sleep 2; done']
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-video-service-config
        - secretRef:
            name: {{ .Release.Name}}-video-service-secret

      - name: alembic-migrate
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}  # Используем тот же образ
        command: ["alembic", "upgrade", "head"]  # Команда для миграций
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-video-service-config # Те же переменные, что у основного контейнера
        - secretRef:
            name: {{ .Release.Name}}-video-service-secret 
        resources:
          limits:
            cpu: "0.5" 
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
      
      - name: check-rabbitmq
        image: busybox
        env:
          - name: RABBITMQ_HOST
            value: {{ .Values.rabbitmq.host}}
          - name: RABBITMQ_USER
            value: {{ .Values.rabbitmq.user }}
          - name: RABBITMQ_PASSWORD
            value: {{ .Values.rabbitmq.password }}
        command: ['sh', '-c', 'until wget http://$RABBITMQ_USER:$RABBITMQ_PASSWORD@$RABBITMQ_HOST:15672/api/aliveness-test/%2F; do echo waiting; sleep 5; done;']


      containers:
      - name: backend      # Имя контейнера
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}  # Образ из Docker Hub/private registry
        command: ["uvicorn"]
        args: ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:  
        - containerPort: {{ .Values.httpPort }}  # Порт, который слушает FastAPI (uvicorn)
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-video-service-config
        - secretRef:
            name: {{ .Release.Name}}-video-service-secret

        resources:            # Ограничения CPU/RAM (опционально)
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"