apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-db
  labels:
    app: video-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-db
  template:
    metadata:
      labels:
        app: video-db 
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432  
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: video-svc-config
              key: DB_NAME 
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: video-svc-secrets
              key: DB_USER 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: video-svc-secrets
              key: DB_PASS 
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc