apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  # доступ на чтение и запись для 1 пода одновременно
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # размер диска