apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: video-service-monitor
  namespace: monitoring  # Где развернут ServiceMonitor
spec:
  selector:
    matchLabels:
      app: video-service  # Ищет Service с этими labels
  namespaceSelector:
    matchNames:
    - default  # Искать во всех namespace (или указать конкретные)
  endpoints:
  - port: web
    path: /metrics  # Путь к метрикам
    interval: 30s  # Частота сбора
    scheme: http   # Протокол (http/https)
    honorLabels: true  # Не перезаписывать labels метрик