"""empty message

Revision ID: 09c3d4b1fa6e
Revises: ffa1b6e1c3b2
Create Date: 2025-06-03 09:21:59.215050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c3d4b1fa6e'
down_revision: Union[str, None] = 'ffa1b6e1c3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'videos', ['video_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='unique')
    # ### end Alembic commands ###
