apiVersion: apps/v1         # Версия API для Deployment
kind: Deployment            # Тип ресурса — Deployment
metadata:
  name: video-service  # Имя деплоймента
  labels:
    app: video-service            # Лейбл для связи с Service
spec:
  replicas: 1              # Количество копий Pod'ов
  selector:
    matchLabels:
      app: video-service         # Выбор Pod'ов по лейблу
  template:                # Шаблон Pod'а
    metadata:
      labels:
        app: video-service       # Лейбл Pod'а (должен совпадать с selector.matchLabels)
    spec:
      containers:
      - name: backend      # Имя контейнера
        image: andrewsmooth/video-service:latest  # Образ из Docker Hub/private registry
        ports:  
        - containerPort: 8000  # Порт, который слушает FastAPI (uvicorn)
        envFrom:
        - configMapRef:
            name: upload-service-config
        - secretRef:
            name: video-svc-secrets 

        resources:            # Ограничения CPU/RAM (опционально)
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"