apiVersion: v1
kind: Service
metadata:
  name: video-service
  labels:
    app: video-service
spec:
  type: ClusterIP 
  selector:
    app: video-service
  ports:
  - name: web
    port: 8000
    targetPort: 8000
  # - name: monitor
  #   port: 8081
  #   targetPort: 8081