apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.host }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.db.host }} # Связь с Pod'ами БД
  ports:
  - port: {{ .Values.db.port }}
    targetPort: {{ .Values.db.port }}