name: Deploy to Yandex Cloud Kubernetes

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up project
        uses: VideoHosting-Platform/actions/.github/actions/setup-and-deploy@main
        with:
          registry: 'ghcr.io'
          folder_id: '${{ secrets.FOLDER_ID }}'
          cluster_id: '${{ secrets.CLUSTER_ID }}'
          token: ${{ secrets.TOKEN }}
          yc_service_account_key: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Kubernetes
        run: |
          helm upgrade video-hosting \
            oci://ghcr.io/video-hosting-platform/charts/video-hosting-stack \
            --reuse-values \
            --set 'videoService.image.tag=${{ github.sha }}'
